version: '3.7'
services:
  tendermint-init:
    image: tendermint/tendermint:v0.32.8
    command: init
    volumes:
        - tendermint-storage:/tendermint
  tendermint:
    depends_on:
      - tendermint-init
      - hciteservice
    image: tendermint/tendermint:v0.32.8
    command: node --rpc.laddr=tcp://0.0.0.0:26657 --proxy_app=tcp://hciteservice:26658
    volumes:
      - tendermint-storage:/tendermint
    restart: always
    ports:
      - "26656-26657:26656-26657"
  hciteservice:
    build:
      context: ../.
      dockerfile: Dockerfile.prebake
    image: hs-abci:test
    depends_on:
      - iavl
    environment:
     - STATS_PORT=9200
     - IAVL_HOST=iavl
     - IAVL_PORT=8090
    restart: always
    entrypoint: /usr/local/bin/hciteservice
    ports:
      - "9200"
    expose:
      - "26658"
      - "9200"
  iavl:
    image: foamspace/iavl:latest
    command: /iavlserver  -db-name "test" -datadir "."  -grpc-endpoint "0.0.0.0:8090"  -gateway-endpoint "0.0.0.0:8091"
    ports:
     - "8090-8091:8091-8091"
    expose:
     - "8090"
     - "8091"
volumes:
  tendermint-storage:
          driver: local
          driver_opts:
                  o: bind
                  type: none
                  device: /tmp/tendermint-storage
