name:                hciteservice
version:             0.1.0.0
github:              "hasanalrasyid/hciteservice"
license:             Apache
author:              "Hasan al Rasyid"
maintainer:          "hasanalrasyid.har@gmail.com"
copyright:           "2020 Hasan al Rasyid"

description:         Please see the README on GitHub at <https://github.com/hasanalrasyid/hciteservice/README.md>

extra-source-files:
- README.md

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds

dependencies:
  - common
  - proto3-wire

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - base >= 4.7 && < 5
    - bloodhound
    - errors
    - hs-abci-extra
    - hs-abci-server
    - hs-abci-sdk
    - hs-abci-types
    - http-client
    - katip
    - katip-elasticsearch
    - lens
    - polysemy
    - polysemy-plugin
    - proto3-suite
    - servant
    - string-conversions
    - text
    - validation
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  exposed-modules:
  - Hciteservice.Application
  - Hciteservice.Config
  - Hciteservice.Aeson
  - Hciteservice.Server
  - Hciteservice.Modules.Hciteservice
  - Hciteservice.Modules.Hciteservice.Messages
  - Hciteservice.Modules.Hciteservice.Types
  - Hciteservice.Modules.Hciteservice.Store
  - Hciteservice.Modules.Hciteservice.Keeper
  - Hciteservice.Modules.Hciteservice.Query
  - Hciteservice.Modules.Hciteservice.Router

executables:
  hciteservice:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-abci-sdk
    - katip
    - lens
    - hciteservice

  gen-protos-exe:
    main:                Main.hs
    source-dirs:         protogen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-casing
    - base
    - bytestring
    - hs-abci-sdk
    - hciteservice
    - pretty
    - proto3-suite
    - proto3-wire

  interact:
    main:                Main.hs
    source-dirs:         interact
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    dependencies:
    - async
    - base
    - data-default-class
    - faker
    - mtl
    - hciteservice
    - hs-abci-sdk
    - hs-abci-test-utils
    - hs-tendermint-client
    - random-strings
    - servant
    - string-conversions
    - text

